sudo: true
language: java

script:
  - cd test; npm install; cd ..
  - make test
  - make js
  - make jstest
  - make jar && make clojars-push

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
  - chmod +x linux-install-1.10.1.466.sh
  - sudo ./linux-install-1.10.1.466.sh
  - nvm install 10.16.0

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cljs
    - $HOME/.gitlibs
    - $TRAVIS_BUILD_DIR/test/node_modules
    - .cpcache

deploy:
  provider: gcs
  access_key_id: "GOOG1EXAFULAKIVE2XMHCT2R6AUQM5JQYCDOTJCGQYHQ3PL6UAREPLNNKVUQA"
  bucket: "jute-demo-site"
  skip_cleanup: true
  acl: public-read
  local-dir: demo
