sudo: true
language: java
script:
  - cd test && npm install
  - make test
  - make js
  - make jstest

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
  - chmod +x linux-install-1.10.1.466.sh
  - sudo ./linux-install-1.10.1.466.sh
  - nvm install 10.16.0

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cljs
    - $HOME/.gitlibs
    - $TRAVIS_BUILD_DIR/test/node_modules
    - .cpcache
