language: java

jdk:
- openjdk11

install:
- curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
- chmod +x linux-install-1.10.1.466.sh
- sudo ./linux-install-1.10.1.466.sh
- nvm install 10.16.0

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cljs"
  - "$HOME/.gitlibs"
  - "$TRAVIS_BUILD_DIR/test/node_modules"
  - ".cpcache"

script:
- cd test; npm install; cd ..
- make test
- make js
- make jstest
- make jar
- make demo

deploy:
- provider: gcs
  edge: true
  bucket: jute-demo-site
  skip_cleanup: true
  local_dir: demo
  acl: public-read
  on:
    branch: master

- provider: script
  script: make clojars-push
  on:
    branch: master
